name: Format

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - ".github/workflows/**.yml"

jobs:
  formatting:
    name: Format files
    runs-on: ubuntu-latest

    steps:
    #----------------------------------------------
    #       check-out repo and set-up python
    #----------------------------------------------
    - uses: actions/checkout@v3
    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    #----------------------------------------------
    #      load cached poetry if cache exists
    #----------------------------------------------
    - name: Load cached Poetry installation
      uses: actions/cache@v3
      with:
        path: ~/.local  # the path depends on the OS
        key: poetry-0  # increment to reset cache

    #----------------------------------------------
    #         install and configure poetry
    #----------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    #----------------------------------------------
    #       load cached venv if cache exists
    #----------------------------------------------
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-0

    #----------------------------------------------
    # install dependencies if cache does not exist
    #----------------------------------------------
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction

    #----------------------------------------------
    #          install and run formatters
    #----------------------------------------------
    - name: Run formatters
      run: poetry run task format

    #----------------------------------------------
    #                commit changes
    #----------------------------------------------
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply yapf and isort formatting
