name: Format

on:
  pull_request:
  push:
    branches:
      - main
    # paths:
    #   - "**.py"

jobs:
  formatting:
    name: Format files
    runs-on: ubuntu-latest

    steps:
    #----------------------------------------------
    #       check-out repo and set-up python
    #----------------------------------------------
    - uses: actions/checkout@v2
    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    #----------------------------------------------
    #          install and run formatters
    #----------------------------------------------
    - name: Run formatters
      run: |
        python -m pip install toml yapf isort
        yapf -r -i .
        isort .

    #----------------------------------------------
    #                commit changes
    #----------------------------------------------
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply yapf and isort formatting
