name: Lint

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - ".github/workflows/**.yml"

jobs:
  linting:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
    #----------------------------------------------
    #       check-out repo and set-up python
    #----------------------------------------------
    - uses: actions/checkout@v2
    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    #----------------------------------------------
    #        load pip cache if cache exists
    #----------------------------------------------
    - name: Load cached pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
        restore-keys: ${{ runner.os }}-pip

    #----------------------------------------------
    #          install and run linters
    #----------------------------------------------
    - name: Run linters
      run: |
        pwd
        python -m pip install flake8 mypy
        flake8 --statistics .
        mypy --strict --pretty .
