# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches:
      - main
    # paths:
    #   - "**.py"

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest]

    steps:
    #----------------------------------------------
    #       check-out repo and set-up python
    #----------------------------------------------
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    #----------------------------------------------
    #         install and configure poetry
    #----------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false
        virtualenvs-in-project: false

    #----------------------------------------------
    #             install dependencies
    #----------------------------------------------
    - name: Install dependencies
      run: poetry install --no-interaction

    #----------------------------------------------
    #                run test suite
    #----------------------------------------------
    - name: Run tests
      run: poetry run coverage run -m pytest

  upload:
    name: Upload coverage data to coveralls.io
    needs: test
    runs-on: ubuntu-latest

    steps:
    #----------------------------------------------
    #       check-out repo and set-up python
    #----------------------------------------------
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2

    #----------------------------------------------
    #         install and configure poetry
    #----------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false
        virtualenvs-in-project: false

    #----------------------------------------------
    #             install dependencies
    #----------------------------------------------
    - name: Install dependencies
      run: poetry install --no-interaction

    #----------------------------------------------
    #         upload data to coveralls.io
    #----------------------------------------------
    - name: Upload coverage data to coveralls.io
      run: |
        poetry run coverage run -m pytest
        poetry run coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
